@baseUrl = http://localhost:3000/api/v1

### register

POST {{baseUrl}}/register
Content-Type: application/json

{   
"firstName": "Bob",
"lastName": "Gaur",
"email": "bob12@gmail.com",
"password": "bob567899",
"password2": "bob567899"
}

### login
# @name LoginRequest
POST {{baseUrl}}/login
Content-Type: application/json

{
"email": "bob12@gmail.com",
"password": "bob567899"
}
### taking token
@token = {{LoginRequest.response.body.token}}

### Get profile
GET {{baseUrl}}/profile

### Logout
GET {{baseUrl}}/logout

### get top headline from newsAPI

GET {{baseUrl}}/news

### search news by keyword

POST {{baseUrl}}/search
Content-Type: application/json

{
    "search": "bitcoin"
}


### weather

POST {{baseUrl}}/weather
Content-Type: application/json

{
    "city": "Delhi"
}